using AA.PMTOGO.DAL;
using AA.PMTOGO.Models.Entities;
using AA.PMTOGO.Services.Interfaces;

namespace AA.PMTOGO.Logging
{
    public class Logger : ILogger
    {
        private readonly ILoggerDAO _loggerDAO;

        public Logger(ILoggerDAO loggerDAO)
        {
            _loggerDAO = loggerDAO;
        }

        public async Task Log(string requestName, byte logLevel, LogCategory logCategory, object result)
        {

            Log log = new()     //create logEntry
            {
                LogLevel = logLevel,
                Category = logCategory.ToString(),
                Message = result.ToString()!,
                Operation = requestName
                //Timestamp is autogenerated with a new instance of Log
            };

            await _loggerDAO.InsertLog(log);

        }
    }
}
